### ISSUE TITLE
x264-specific options are used for VP9 and AV1

### ISSUE THREAD

**Issue by EnderEyeGames** [zeopticz/file-compressor#1]
No matter what codec is selected, the script will attempt to use `-preset` to select the speed. This is correct for x264 and x265, but it will do nothing and trigger a warning on libvpx-vp9 and libaom-av1. VP9 instead uses `-deadline`, `-cpu-used`, and `-row-mt` to control speed, while AV1 uses `-cpu-used`, `-row-mt`, `-tiles`, and myriad other options.

**Comment by zeopticz** [comment]
will fix in the next update, thanks!
